CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(50)                             NOT NULL,
    email   VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests
(
    request_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description   VARCHAR(1000)                           NOT NULL,
    creation_time TIMESTAMP DEFAULT NOW()                 NOT NULL,
    requester_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (request_id),
    CONSTRAINT fk_requester FOREIGN KEY (requester_id) REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS items
(
    item_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(200)                            NOT NULL,
    description  VARCHAR(1000)                           NOT NULL,
    is_available BOOLEAN                                 NOT NULL,
    owner_id     BIGINT                                  NOT NULL,
    request_id   BIGINT DEFAULT NULL,
    CONSTRAINT pk_item PRIMARY KEY (item_id),
    CONSTRAINT fk_owner FOREIGN KEY (owner_id) REFERENCES users (user_id),
    CONSTRAINT fk_request FOREIGN KEY (request_id) REFERENCES requests (request_id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_time TIMESTAMP                               NOT NULL,
    end_time   TIMESTAMP                               NOT NULL,
    item_id    BIGINT                                  NOT NULL,
    booker_id  BIGINT                                  NOT NULL,
    status     VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_booking PRIMARY KEY (booking_id),
    CONSTRAINT fk_item_booking FOREIGN KEY (item_id) REFERENCES items (item_id) ON DELETE CASCADE,
    CONSTRAINT fk_booker FOREIGN KEY (booker_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments
(
    comment_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text          VARCHAR(1000)                           NOT NULL,
    author_id     BIGINT                                  NOT NULL,
    item_id       BIGINT                                  NOT NULL,
    creation_time TIMESTAMP                               NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_comment PRIMARY KEY (comment_id),
    CONSTRAINT fk_author FOREIGN KEY (author_id) REFERENCES users (user_id),
    CONSTRAINT fk_item_comment FOREIGN KEY (item_id) REFERENCES items (item_id)
);
