CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(50)                             NOT NULL,
    email   VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS item_requests
(
    item_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description     VARCHAR(1000)                           NOT NULL,
    creation_time   TIMESTAMP                               NOT NULL DEFAULT NOW(),
    requester_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (item_request_id),
    CONSTRAINT fk_requester FOREIGN KEY (requester_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS items
(
    item_id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(200)                            NOT NULL,
    description     VARCHAR(1000)                           NOT NULL,
    is_available    BOOLEAN                                 NOT NULL,
    owner_id        BIGINT                                  NOT NULL,
    item_request_id BIGINT DEFAULT NULL,
    CONSTRAINT pk_item PRIMARY KEY (item_id),
    CONSTRAINT fk_owner FOREIGN KEY (owner_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_request FOREIGN KEY (item_request_id) REFERENCES item_requests (item_request_id) ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS item_bookings
(
    item_booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_time      TIMESTAMP                               NOT NULL,
    end_time        TIMESTAMP                               NOT NULL,
    item_id         BIGINT                                  NOT NULL,
    booker_id       BIGINT                                  NOT NULL,
    status          VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_booking PRIMARY KEY (item_booking_id),
    CONSTRAINT fk_item_booking FOREIGN KEY (item_id) REFERENCES items (item_id) ON DELETE CASCADE,
    CONSTRAINT fk_booker FOREIGN KEY (booker_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS item_comments
(
    item_comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text            VARCHAR(1000)                           NOT NULL,
    author_id       BIGINT                                  NOT NULL,
    item_id         BIGINT                                  NOT NULL,
    creation_time   TIMESTAMP                               NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_comment PRIMARY KEY (item_comment_id),
    CONSTRAINT fk_author FOREIGN KEY (author_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_item_comment FOREIGN KEY (item_id) REFERENCES items (item_id) ON DELETE CASCADE
);
